"""enhance_audit_log_model

Revision ID: 4dba8d45567f
Revises: f6281f8ea22c
Create Date: 2026-07-21 21:46:18.515329

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4dba8d45567f'
down_revision: Union[str, Sequence[str], None] = 'f6281f8ea22c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('audit_logs', sa.Column('old_value', sa.Text(), nullable=True))
    op.add_column('audit_logs', sa.Column('new_value', sa.Text(), nullable=True))
    op.add_column('audit_logs', sa.Column('ip_address', sa.String(length=50), nullable=True))
    op.add_column('audit_logs', sa.Column('user_agent', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('audit_logs', 'user_agent')
    op.drop_column('audit_logs', 'ip_address')
    op.drop_column('audit_logs', 'new_value')
    op.drop_column('audit_logs', 'old_value')
    # ### end Alembic commands ###
