"""Convert role to enum

Revision ID: 97891f6aeecd
Revises: 820959f45bfa
Create Date: 2026-07-19 16:48:57.420767

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '97891f6aeecd'
down_revision: Union[str, Sequence[str], None] = '820959f45bfa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'role',
               existing_type=sa.VARCHAR(length=30),
               type_=sa.Enum('ADMIN', 'CONTROLLER', 'SUPERVISOR', 'LOBBY_OPERATOR', 'VIEWER', name='userrole'),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'role',
               existing_type=sa.Enum('ADMIN', 'CONTROLLER', 'SUPERVISOR', 'LOBBY_OPERATOR', 'VIEWER', name='userrole'),
               type_=sa.VARCHAR(length=30),
               existing_nullable=False)
    # ### end Alembic commands ###
