"""Add is_active/is_imported flags, enhance main_data and archive_data

Revision ID: e10baefcaf46
Revises: 4dba8d45567f
Create Date: 2026-07-21 22:17:25.348587

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e10baefcaf46'
down_revision: Union[str, Sequence[str], None] = '4dba8d45567f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('archive_data', sa.Column('crew_id', sa.String(length=20), nullable=False))
    op.add_column('archive_data', sa.Column('crew_name', sa.String(length=100), nullable=False))
    op.add_column('archive_data', sa.Column('train_no', sa.String(length=20), nullable=False))
    op.add_column('archive_data', sa.Column('from_station', sa.String(length=20), nullable=False))
    op.add_column('archive_data', sa.Column('to_station', sa.String(length=20), nullable=False))
    op.add_column('archive_data', sa.Column('status', sa.String(length=30), nullable=False))
    op.add_column('archive_data', sa.Column('sign_on_time', sa.String(length=30), nullable=False))
    op.add_column('archive_data', sa.Column('cto_train_no', sa.String(length=20), nullable=False))
    op.add_column('archive_data', sa.Column('cto_station', sa.String(length=20), nullable=False))
    op.add_column('archive_data', sa.Column('cto_time', sa.String(length=30), nullable=False))
    op.add_column('archive_data', sa.Column('loco1', sa.String(length=20), nullable=False))
    op.add_column('archive_data', sa.Column('loco2', sa.String(length=20), nullable=False))
    op.add_column('archive_data', sa.Column('loco3', sa.String(length=20), nullable=False))
    op.add_column('archive_data', sa.Column('shed', sa.String(length=30), nullable=False))
    op.add_column('archive_data', sa.Column('is_active', sa.Boolean(), nullable=False))
    op.create_index(op.f('ix_archive_data_crew_id'), 'archive_data', ['crew_id'], unique=False)
    op.add_column('cms_data', sa.Column('is_active', sa.Boolean(), nullable=False))
    op.add_column('cms_data', sa.Column('is_imported', sa.Boolean(), nullable=False))
    op.add_column('main_data', sa.Column('crew_id', sa.String(length=20), nullable=False))
    op.add_column('main_data', sa.Column('crew_name', sa.String(length=100), nullable=False))
    op.add_column('main_data', sa.Column('train_no', sa.String(length=20), nullable=False))
    op.add_column('main_data', sa.Column('from_station', sa.String(length=20), nullable=False))
    op.add_column('main_data', sa.Column('to_station', sa.String(length=20), nullable=False))
    op.add_column('main_data', sa.Column('status', sa.String(length=30), nullable=False))
    op.add_column('main_data', sa.Column('sign_on_time', sa.String(length=30), nullable=False))
    op.add_column('main_data', sa.Column('cto_train_no', sa.String(length=20), nullable=False))
    op.add_column('main_data', sa.Column('cto_station', sa.String(length=20), nullable=False))
    op.add_column('main_data', sa.Column('cto_time', sa.String(length=30), nullable=False))
    op.add_column('main_data', sa.Column('loco1', sa.String(length=20), nullable=False))
    op.add_column('main_data', sa.Column('loco2', sa.String(length=20), nullable=False))
    op.add_column('main_data', sa.Column('loco3', sa.String(length=20), nullable=False))
    op.add_column('main_data', sa.Column('shed', sa.String(length=30), nullable=False))
    op.add_column('main_data', sa.Column('is_active', sa.Boolean(), nullable=False))
    op.create_index(op.f('ix_main_data_crew_id'), 'main_data', ['crew_id'], unique=False)
    op.add_column('signon_data', sa.Column('is_active', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('signon_data', 'is_active')
    op.drop_index(op.f('ix_main_data_crew_id'), table_name='main_data')
    op.drop_column('main_data', 'is_active')
    op.drop_column('main_data', 'shed')
    op.drop_column('main_data', 'loco3')
    op.drop_column('main_data', 'loco2')
    op.drop_column('main_data', 'loco1')
    op.drop_column('main_data', 'cto_time')
    op.drop_column('main_data', 'cto_station')
    op.drop_column('main_data', 'cto_train_no')
    op.drop_column('main_data', 'sign_on_time')
    op.drop_column('main_data', 'status')
    op.drop_column('main_data', 'to_station')
    op.drop_column('main_data', 'from_station')
    op.drop_column('main_data', 'train_no')
    op.drop_column('main_data', 'crew_name')
    op.drop_column('main_data', 'crew_id')
    op.drop_column('cms_data', 'is_imported')
    op.drop_column('cms_data', 'is_active')
    op.drop_index(op.f('ix_archive_data_crew_id'), table_name='archive_data')
    op.drop_column('archive_data', 'is_active')
    op.drop_column('archive_data', 'shed')
    op.drop_column('archive_data', 'loco3')
    op.drop_column('archive_data', 'loco2')
    op.drop_column('archive_data', 'loco1')
    op.drop_column('archive_data', 'cto_time')
    op.drop_column('archive_data', 'cto_station')
    op.drop_column('archive_data', 'cto_train_no')
    op.drop_column('archive_data', 'sign_on_time')
    op.drop_column('archive_data', 'status')
    op.drop_column('archive_data', 'to_station')
    op.drop_column('archive_data', 'from_station')
    op.drop_column('archive_data', 'train_no')
    op.drop_column('archive_data', 'crew_name')
    op.drop_column('archive_data', 'crew_id')
    # ### end Alembic commands ###
