"""Initial railway workflow

Revision ID: f0d3b5764037
Revises: 
Create Date: 2026-07-21 20:40:31.162640

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f0d3b5764037'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('actor_username', sa.String(length=100), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('entity', sa.String(length=100), nullable=False),
    sa.Column('entity_id', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_id'), 'audit_logs', ['id'], unique=False)
    op.create_table('cms_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('crew_id', sa.String(length=20), nullable=False),
    sa.Column('crew_name', sa.String(length=100), nullable=False),
    sa.Column('crew_designation', sa.String(length=50), nullable=False),
    sa.Column('fortnight_hours', sa.String(length=20), nullable=False),
    sa.Column('avail_time', sa.String(length=30), nullable=False),
    sa.Column('avail_station', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('called_time', sa.String(length=30), nullable=False),
    sa.Column('ack_time', sa.String(length=30), nullable=False),
    sa.Column('sign_on_time', sa.String(length=30), nullable=False),
    sa.Column('last_signoff_time', sa.String(length=30), nullable=False),
    sa.Column('train_no', sa.String(length=20), nullable=False),
    sa.Column('from_station', sa.String(length=20), nullable=False),
    sa.Column('to_station', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cms_data_crew_id'), 'cms_data', ['crew_id'], unique=False)
    op.create_index(op.f('ix_cms_data_id'), 'cms_data', ['id'], unique=False)
    op.create_table('crew',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('crew_id', sa.String(length=50), nullable=False),
    sa.Column('full_name', sa.String(length=100), nullable=False),
    sa.Column('department', sa.Enum('Driver', 'Conductor', 'PlatformStaff', 'Security', 'Maintenance', 'AdminStaff', name='department', native_enum=False), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('crew_id'),
    sa.UniqueConstraint('email')
    )
    op.create_index(op.f('ix_crew_id'), 'crew', ['id'], unique=False)
    op.create_table('import_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_import_logs_id'), 'import_logs', ['id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('full_name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('Admin', 'Controller', 'Supervisor', 'LobbyOperator', 'Viewer', name='userrole', native_enum=False), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('signon_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cms_id', sa.Integer(), nullable=False),
    sa.Column('crew_id', sa.String(length=20), nullable=False),
    sa.Column('crew_name', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('train_no', sa.String(length=20), nullable=False),
    sa.Column('from_station', sa.String(length=20), nullable=False),
    sa.Column('to_station', sa.String(length=20), nullable=False),
    sa.Column('sign_on_time', sa.String(length=30), nullable=False),
    sa.Column('cto_train_no', sa.String(length=20), nullable=False),
    sa.Column('cto_station', sa.String(length=20), nullable=False),
    sa.Column('cto_time', sa.String(length=30), nullable=False),
    sa.Column('loco1', sa.String(length=20), nullable=False),
    sa.Column('loco2', sa.String(length=20), nullable=False),
    sa.Column('loco3', sa.String(length=20), nullable=False),
    sa.Column('shed', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['cms_id'], ['cms_data.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('archive_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('signon_id', sa.Integer(), nullable=False),
    sa.Column('archived_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['signon_id'], ['signon_data.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('main_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('signon_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['signon_id'], ['signon_data.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('main_data')
    op.drop_table('archive_data')
    op.drop_table('signon_data')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_import_logs_id'), table_name='import_logs')
    op.drop_table('import_logs')
    op.drop_index(op.f('ix_crew_id'), table_name='crew')
    op.drop_table('crew')
    op.drop_index(op.f('ix_cms_data_id'), table_name='cms_data')
    op.drop_index(op.f('ix_cms_data_crew_id'), table_name='cms_data')
    op.drop_table('cms_data')
    op.drop_index(op.f('ix_audit_logs_id'), table_name='audit_logs')
    op.drop_table('audit_logs')
    # ### end Alembic commands ###
