"""Update crew model

Revision ID: f6281f8ea22c
Revises: f0d3b5764037
Create Date: 2026-07-21 20:45:33.604028

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f6281f8ea22c'
down_revision: Union[str, Sequence[str], None] = 'f0d3b5764037'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('crew', sa.Column('mobile_number', sa.String(length=15), nullable=False))
    op.add_column('crew', sa.Column('password_hash', sa.String(length=255), nullable=False))
    op.add_column('crew', sa.Column('designation', sa.String(length=50), nullable=False))
    op.drop_constraint(op.f('crew_crew_id_key'), 'crew', type_='unique')
    op.drop_constraint(op.f('crew_email_key'), 'crew', type_='unique')
    op.create_index(op.f('ix_crew_crew_id'), 'crew', ['crew_id'], unique=True)
    op.create_unique_constraint(None, 'crew', ['mobile_number'])
    op.drop_column('crew', 'email')
    op.drop_column('crew', 'phone')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('crew', sa.Column('phone', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    op.add_column('crew', sa.Column('email', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'crew', type_='unique')
    op.drop_index(op.f('ix_crew_crew_id'), table_name='crew')
    op.create_unique_constraint(op.f('crew_email_key'), 'crew', ['email'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('crew_crew_id_key'), 'crew', ['crew_id'], postgresql_nulls_not_distinct=False)
    op.drop_column('crew', 'designation')
    op.drop_column('crew', 'password_hash')
    op.drop_column('crew', 'mobile_number')
    # ### end Alembic commands ###
